### ISSUE TITLE
Error enabling Pricing Management in Odoo

### ISSUE THREAD

**Issue by aignermi** [OCA/connector-magento#106]
hi guys,

when I want to enable the pricing management in odoo at the connector settings, I get the following error:

Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/8.0/openerp/http.py", line 536, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/8.0/openerp/http.py", line 573, in dispatch
    result = self._call_function(*_self.params)
  File "/home/odoo/src/odoo/8.0/openerp/http.py", line 309, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/http.py", line 306, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/odoo/src/odoo/8.0/openerp/http.py", line 802, in __call__
    return self.method(_args, *_kw)
  File "/home/odoo/src/odoo/8.0/openerp/http.py", line 402, in response_wrap
    response = f(_args, *_kw)
  File "/home/odoo/src/custom/private/loempia/controllers/embed.py", line 49, in download_urls
    mods_to_install = Modules.compute_modules_to_install(series, module_names, local_modules)
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/odoo/src/custom/private/loempia/loempia2.py", line 959, in compute_modules_to_install
    assert len(mids) == len(set(requested_mods)), 'Unknown modules requested: %r' % requested_mods
AssertionError: Unknown modules requested: ['magentoerpconnect_pricing']

How can I install that?

Thanks,
Michael

**Comment by guewen** [comment]
This module has been migrated here #92 and still needs to be reviewed and tested. You can merge that branch in yours and test it, then you would be kind to share your review on the pull request.
