### ISSUE TITLE
Synchhronizing metadata fails

### ISSUE THREAD

**Issue by loyalcomps** [OCA/connector-magento#122]
I get the following error in odoo 8.0

Odoo Server Error
Traceback (most recent call last):
  File "/opt/loyalerp/loyalerp-server/openerp/http.py", line 536, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/loyalerp/loyalerp-server/openerp/http.py", line 573, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/loyalerp/loyalerp-server/openerp/http.py", line 309, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/loyalerp/loyalerp-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/loyalerp/loyalerp-server/openerp/http.py", line 306, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/loyalerp/loyalerp-server/openerp/http.py", line 802, in __call__
    return self.method(_args, *_kw)
  File "/opt/loyalerp/loyalerp-server/openerp/http.py", line 402, in response_wrap
    response = f(_args, *_kw)
  File "/opt/loyalerp/loyalerp-server/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/loyalerp/loyalerp-server/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/loyalerp/loyalerp-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/loyalerp/loyalerp-server/openerp/api.py", line 363, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/loyalerp/custom/magnetoconnector/connector-magento/magentoerpconnect/magento_model.py", line 198, in synchronize_metadata
    import_batch(session, model, backend.id)
  File "/opt/loyalerp/custom/magnetoconnector/connector-magento/magentoerpconnect/unit/import_synchronizer.py", line 370, in import_batch
    importer.run(filters=filters)
  File "/opt/loyalerp/custom/magnetoconnector/connector-magento/magentoerpconnect/unit/import_synchronizer.py", line 239, in run
    record_ids = self.backend_adapter.search(filters)
  File "/opt/loyalerp/custom/magnetoconnector/connector-magento/magentoerpconnect/unit/backend_adapter.py", line 211, in search
    [filters] if filters else [{}])
  File "/opt/loyalerp/custom/magnetoconnector/connector-magento/magentoerpconnect/unit/backend_adapter.py", line 159, in _call
    full_url=custom_url) as api:
  File "/usr/local/lib/python2.7/dist-packages/magento/api.py", line 133, in __enter__
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/magento/api.py", line 123, in connect
    self.client = ServerProxy(self.url, allow_none=True)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1549, in **init**
    raise IOError, "unsupported XML-RPC protocol"
IOError: unsupported XML-RPC protocol

**Comment by guewen** [comment]
The URL that you use is not recognized as a valid XML-RPC server.
Check if you use `http://` or `https://`, also the URL should not include `/api/xmlrpc`.

**Comment by loyalcomps** [comment]
Thank you. That worked.
