### ISSUE TITLE
ImportError: cannot import name setting

### ISSUE THREAD

**Issue by mdemirell** [OCA/connector-magento#127]
My Odoo 8.0 running on Windows 7 Ultimate
But, it gives an error when installing the module magentoerpconnect.

Traceback (most recent call last):
  File "C:\Odoo 8.0\server.\openerp\http.py", line 537, in _handle_exception
  File "C:\Odoo 8.0\server.\openerp\http.py", line 574, in dispatch
  File "C:\Odoo 8.0\server.\openerp\http.py", line 310, in _call_function
  File "C:\Odoo 8.0\server.\openerp\service\model.py", line 113, in wrapper
  File "C:\Odoo 8.0\server.\openerp\http.py", line 307, in checked_call
  File "C:\Odoo 8.0\server.\openerp\http.py", line 803, in __call__
  File "C:\Odoo 8.0\server.\openerp\http.py", line 403, in response_wrap
  File "C:\Odoo 8.0\server\openerp\addons\web\controllers\main.py", line 948, in call_button
  File "C:\Odoo 8.0\server\openerp\addons\web\controllers\main.py", line 936, in _call_kw
  File "C:\Odoo 8.0\server.\openerp\api.py", line 241, in wrapper
  File "C:\Odoo 8.0\server.\openerp\api.py", line 394, in old_api
  File "C:\Odoo 8.0\server.\openerp\api.py", line 398, in new_api
  File "C:\Odoo 8.0\server\openerp\addons\base\module\wizard\base_module_update.py", line 15, in update_module
  File "C:\Odoo 8.0\server.\openerp\api.py", line 239, in wrapper
  File "C:\Odoo 8.0\server.\openerp\api.py", line 463, in new_api
  File "C:\Odoo 8.0\server\openerp\addons\base\module\module.py", line 650, in update_list
  File "C:\Odoo 8.0\server.\openerp\http.py", line 1308, in load_addons
  File "C:\Odoo 8.0\server.\openerp\modules\module.py", line 80, in load_module
  File "C:\Odoo 8.0\server\openerp\addons\magentoerpconnect__init__.py", line 2, in <module>
ImportError: cannot import name setting

**Comment by guewen** [comment]
Is the traceback complete? Do you have another error above?

**Comment by ghost** [comment]
I had this same issue because I had not installed magento python extension (pip install magento or easy_install magento).

Try that and see if that is your issue too.

**Comment by Stefano7777777** [comment]
hi, have you resolved?
i've the same error when try to install magento connector can you help me?
i've dona easy_install magento e give this result:
sudo easy_install magento
Password:
Searching for magento
Best match: magento 1.0
Processing magento-1.0-py2.7.egg
magento 1.0 is already the active version in easy-install.pth

Using /Library/Python/2.7/site-packages/magento-1.0-py2.7.egg
Processing dependencies for magento
Finished processing dependencies for magento

this is the error:
Traceback (most recent call last):
  File "/Applications/odoo-8.0-11/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Applications/odoo-8.0-11/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/Applications/odoo-8.0-11/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/Applications/odoo-8.0-11/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/Applications/odoo-8.0-11/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/Applications/odoo-8.0-11/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/Applications/odoo-8.0-11/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/Applications/odoo-8.0-11/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/web/controllers/main.py", line 940, in call_button
    action = self._call_kw(model, method, args, {})
  File "/Applications/odoo-8.0-11/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/Applications/odoo-8.0-11/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/Applications/odoo-8.0-11/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/base/module/module.py", line 722, in install_from_urls
    self.update_list(cr, uid, context=context)
  File "/Applications/odoo-8.0-11/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/Applications/odoo-8.0-11/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/base/module/module.py", line 654, in update_list
    handler.load_addons()
  File "/Applications/odoo-8.0-11/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 1298, in load_addons
    m = __import__('openerp.addons.' + module)
  File "/Applications/odoo-8.0-11/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/modules/module.py", line 80, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/Applications/odoo-8.0-11/apps/odoo/data/addons/8.0/magentoerpconnect/**init**.py", line 2, in <module>
    from . import setting
ImportError: cannot import name setting

**Comment by ghost** [comment]
Yes after I installed the magento python module I restarted odoo and it
worked.

On Mon, Sep 14, 2015 at 10:47 AM, Stefano7777777 notifications@github.com
wrote:

> hi, have you resolved?
> i've the same error when try to install magento connector can you help me?
> i've dona easy_install magento e give this result:
> sudo easy_install magento
> Password:
> Searching for magento
> Best match: magento 1.0
> Processing magento-1.0-py2.7.egg
> magento 1.0 is already the active version in easy-install.pth
> 
> Using /Library/Python/2.7/site-packages/magento-1.0-py2.7.egg
> Processing dependencies for magento
> Finished processing dependencies for magento
> 
> this is the error:
> Traceback (most recent call last):
> File
> "/Applications/odoo-8.0-11/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py",
> line 530, in
> 
> _handle_exception return super(JsonRequest,
> self).handle_exception(exception) File
> "/Applications/odoo-8.0-11/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py",
> line 567, in dispatch result = self._call_function(_self.params) File
> "/Applications/odoo-8.0-11/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py",
> line 303, in _call_function return checked_call(self.db, _args, *kwargs)
> File
> "/Applications/odoo-8.0-11/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/service/model.py",
> line 113, in wrapper return f(dbname, args, *kwargs) File
> "/Applications/odoo-8.0-11/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py",
> line 300, in checked_call return self.endpoint(a, *kw) File
> "/Applications/odoo-8.0-11/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py",
> line 796, in __call_
> return self.method(_args, *_kw)
> File
> "/Applications/odoo-8.0-11/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py",
> line 396, in response_wrap
> response = f(_args, *_kw)
> File
> "/Applications/odoo-8.0-11/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/web/controllers/main.py",
> line 940, in call_button
> action = self.
> 
> _call_kw(model, method, args, {}) File
> "/Applications/odoo-8.0-11/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/web/controllers/main.py",
> line 928, in call_kw return getattr(request.registry.get(model),
> method)(request.cr http://request.cr, request.uid, args, *kwargs) File
> "/Applications/odoo-8.0-11/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py",
> line 241, in wrapper return old_api(self, args, *kwargs) File
> "/Applications/odoo-8.0-11/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/base/module/module.py",
> line 722, in install_from_urls self.update_list(cr, uid, context=context)
> File
> "/Applications/odoo-8.0-11/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py",
> line 241, in wrapper return old_api(self, args, *kwargs) File
> "/Applications/odoo-8.0-11/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/base/module/module.py",
> line 654, in update_list handler.load_addons() File
> "/Applications/odoo-8.0-11/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py",
> line 1298, in load_addons m = __import_('openerp.addons.' + module)
> File
> "/Applications/odoo-8.0-11/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/modules/module.py",
> line 80, in load_module
> mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
> File
> "/Applications/odoo-8.0-11/apps/odoo/data/addons/8.0/magentoerpconnect/
> _init_.py", line 2, in
> from . import setting
> ImportError: cannot import name setting
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OCA/connector-magento/issues/127#issuecomment-140121542
> .

## 

Best Regards,
Mark Meadows
www.apptuate.com
636.678.9924

**Comment by maxicooper** [comment]
Stefano7777777, where you able to solve this? Me too have already installed the Magento python module and a similar error.

**Comment by shaishab** [comment]
I have same error. how can I solve this issue ? can anyone describe me ?
N.B: Installed magento using (pip install magento) in windows 10

**Comment by hbrunn** [comment]
check that you have installed all dependencies of the connector module, which is specifically the python requests module (`pip install requests`)
