### ISSUE TITLE
404 Category not found>

### ISSUE THREAD

**Issue by diezcode** [OCA/connector-magento#142]
Hello, When I'm trying to make a connection in Odoo from Magento, this is my error that I get:

404 Category not found

ProtocolError: ProtocolError for http://magento.contento.ch/api/xmlrpc: 404 Category not found

**Comment by guewen** [comment]
Hi,

your error is incomplete, could you add the full traceback?

**Comment by diezcode** [comment]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 363, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/custom_magento/magentoerpconnect/magento_model.py", line 198, in synchronize_metadata
    import_batch(session, model, backend.id)
  File "/opt/custom_magento/magentoerpconnect/unit/import_synchronizer.py", line 370, in import_batch
    importer.run(filters=filters)
  File "/opt/custom_magento/magentoerpconnect/unit/import_synchronizer.py", line 239, in run
    record_ids = self.backend_adapter.search(filters)
  File "/opt/custom_magento/magentoerpconnect/unit/backend_adapter.py", line 211, in search
    [filters] if filters else [{}])
  File "/opt/custom_magento/magentoerpconnect/unit/backend_adapter.py", line 159, in _call
    full_url=custom_url) as api:
  File "/usr/local/lib/python2.7/dist-packages/magento/api.py", line 136, in __enter__
    self.username, self.password)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in **call**
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1321, in single_request
    response.msg,
ProtocolError: ProtocolError for  http://magento.contento.ch/index.php/api/xmlrpc: 404 Category not found

This is the error I get when I want to synchronize metadata

**Comment by diezcode** [comment]
Ok Sorry for this post, the problem was, that I doesn't connect to the REAL URL-ADRESS.
So I have changed the admin-url adress to the real magento-shop admin panel and it works.

Thanks
