### ISSUE TITLE
ProtocolError: <ProtocolError for MyWebsite/index.php/api/xmlrpc: 403 Forbidden>

### ISSUE THREAD

**Issue by autoslide** [OCA/connector-magento#156]
Hello,

After updating Magento I am unable to sync MICRODATA Odoo8 Magento 1.9.2.1, I have an error like cited in my message titre. Error 403 but when I test my xmlrpc file from my server "wget http://autoslide.fr/index.php/api/xmlrpc" it works fine. If you have an idea for my problem, maybe a problem with magento file permission, i precise my media files are on cdn Cloudflare this could be my problem?
i put exeption error code:

```
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 372, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/.local/share/Odoo/addons/8.0/magentoerpconnect/magento_model.py", line 198, in synchronize_metadata
    import_batch(session, model, backend.id)
  File "/opt/odoo/.local/share/Odoo/addons/8.0/magentoerpconnect/unit/import_synchronizer.py", line 370, in import_batch
    importer.run(filters=filters)
  File "/opt/odoo/.local/share/Odoo/addons/8.0/magentoerpconnect/unit/import_synchronizer.py", line 239, in run
    record_ids = self.backend_adapter.search(filters)
  File "/opt/odoo/.local/share/Odoo/addons/8.0/magentoerpconnect/unit/backend_adapter.py", line 211, in search
    [filters] if filters else [{}])
  File "/opt/odoo/.local/share/Odoo/addons/8.0/magentoerpconnect/unit/backend_adapter.py", line 178, in _call
    return result
  File "/usr/local/lib/python2.7/dist-packages/magento/api.py", line 149, in __exit__
    self.client.endSession(self.session)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1321, in single_request
    response.msg,
ProtocolError: <ProtocolError for autoslide.fr/index.php/api/xmlrpc: 403 Forbidden>
```

Regards

**Comment by autoslide** [comment]
It was security problem with mod-evasive i put cdn ip in white list and its work fine.

**Comment by onlysteg** [comment]
Hi guys, I have the exact same error when I try to export the products from odoo v8.0 to magento 1.9 I use the webkul plugin ... can you tell me how I can fix it? and where should I put the odoo server ip in the white list?

**Comment by onlysteg** [comment]
> It was security problem with mod-evasive i put cdn ip in white list and its work fine.

my error is: index.php/api/xmlrpc: 503 Service Unavailable
