### ISSUE TITLE
Error When importing data in Odoo8-Magento 1.9.2

### ISSUE THREAD

**Issue by puneetaggi** [OCA/connector-magento#167]
Hi

I have installed the Magento conector for Odoo8 and Magento 1.9.2. I am getting following error when I am trying to syncronize data.

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 8.0-20151012\server.\openerp\http.py", line 537, in _handle_exception
  File "C:\Program Files (x86)\Odoo 8.0-20151012\server.\openerp\http.py", line 574, in dispatch
  File "C:\Program Files (x86)\Odoo 8.0-20151012\server.\openerp\http.py", line 310, in _call_function
  File "C:\Program Files (x86)\Odoo 8.0-20151012\server.\openerp\service\model.py", line 113, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20151012\server.\openerp\http.py", line 307, in checked_call
  File "C:\Program Files (x86)\Odoo 8.0-20151012\server.\openerp\http.py", line 803, in __call__
  File "C:\Program Files (x86)\Odoo 8.0-20151012\server.\openerp\http.py", line 403, in response_wrap
  File "C:\Program Files (x86)\Odoo 8.0-20151012\server\openerp\addons\web\controllers\main.py", line 952, in call_button
  File "C:\Program Files (x86)\Odoo 8.0-20151012\server\openerp\addons\web\controllers\main.py", line 940, in _call_kw
  File "C:\Program Files (x86)\Odoo 8.0-20151012\server.\openerp\service\model.py", line 113, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20151012\server\openerp\addons\web\controllers\main.py", line 939, in checked_call
  File "C:\Program Files (x86)\Odoo 8.0-20151012\server.\openerp\api.py", line 250, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20151012\server.\openerp\api.py", line 372, in old_api
  File "C:\Program Files (x86)\Odoo 8.0-20151012\server\openerp\addons\magentoerpconnect\magento_model.py", line 198, in synchronize_metadata
  File "C:\Program Files (x86)\Odoo 8.0-20151012\server\openerp\addons\magentoerpconnect\unit\import_synchronizer.py", line 370, in import_batch
  File "C:\Program Files (x86)\Odoo 8.0-20151012\server\openerp\addons\magentoerpconnect\unit\import_synchronizer.py", line 239, in run
  File "C:\Program Files (x86)\Odoo 8.0-20151012\server\openerp\addons\magentoerpconnect\unit\backend_adapter.py", line 211, in search
  File "C:\Program Files (x86)\Odoo 8.0-20151012\server\openerp\addons\magentoerpconnect\unit\backend_adapter.py", line 156, in _call
AttributeError: 'module' object has no attribute 'API'

Thanks in advance.

Thanks
Puneet

**Comment by guewen** [comment]
Make sure to run `sudo pip install magento`

**Comment by puneetaggi** [comment]
Hi 

I am using the Windows 7 Machine for the setup.

I have issued following command 
pip install python-magento

Also have copied the Magento Folder to C:\Program Files (x86)\Odoo 8.0-20151012\server\werkzeug

Thanks
Puneet

**Comment by guewen** [comment]
I can't help you with Python on Windows. My only advice is to get a GNU/Linux VM or server, nowadays it's easy to setup a virtualbox/vmware/docker with debian, ubuntu or whatever. Not only you should have less issues, but using the same tools as the community means that more people will be able to help you.

**Comment by puneetaggi** [comment]
Thanks Guewen for all help.

I will test the issue in Linux machine.

**Comment by l-arnold** [comment]
@puneetaggi   Do you have capability to run a Virtual Machine?  I couild get you an ISO install that has Odoo and would take the connector quite directly.  I've done an ISO with the connector included, just have a few months of Git between then and now.

Setting up Odoo with the correct dependecies both for Odoo and then for the Connector is the important part.  I like to have my structure take the following structure.

/opt/openerp/odoo
/opt/openerp/odoo/addons  (standard)
/opt/openerp/oca/(then individual oca module directories)

**Comment by puneetaggi** [comment]
Hi Arnold

I have installed the VM VirtualBox and working on installing the Cent OS.

It will be great if you can share your ISO File with me.

Thanks
Puneet

**Comment by l-arnold** [comment]
Puneet, 
You Need to Boot your Server from the ISO Below and install. This will install the Debian OS along with Turnkeylinux and Odoo 8. (you won't need Cent OS). 
You want to set up your VM Environment so that the Virutal Machine boots from the ISO file. You can also Install to a Full Server on Bare Metal if you prefer (ie a dedicated server - not virtual) 

This REQUIRES a 64 Bit Machine or Virtual Environment.  It won't run 32 bit as built.

I recomend an install with 2 Processors, 1-4gb Ram (2GB works well for me).  20 GB HD Space to start.  Post install there are a few settings changes if you want to optimize the Job Runner and Workers to be > 0.

From: https://sourceforge.net/projects/tklnomadicodoo/files/ 
Use the current "most recent 
tkl odoo core 1 master.iso 

This will be coming out on the TurnkeyLinux Libary I understand in a few weeks and you would be able to migrate your data quite easily to Amazon AWS if you like then. 
www.turnkeylinux.org 

Once you get the system running I can talk to you about getting the Connector running. Goes pretty quickly also. (Magento is always a trick but TurnKeyLinux has a  Magento Appliance as well). 

Knock around the Odoo and Debian system a bit before starting with the connector if you would. If you want to "browse" directory structure you can do that through the WebMin interface (Port :12321).. The "File Manager" (GUI based in WebMin) requires Java so you will need Internet Explorer or Firefox to use that aspect. Webshell and the rest of Webmin also work well with Chrome. A good SSH Client like BitVise SSH and FTP Client I highly recommend also. 

check back in when you want to get the connector installed. 
All should be pretty easy. 
Landis Arnold
