### ISSUE TITLE
<Fault 2: 'Access denied.'>

### ISSUE THREAD

**Issue by Ivanio** [OCA/connector-magento#182]
Hello,
i have a problem with the connector. I don't know what i'm doing wrong. I searched all around google and don't find the solution. I have Magento 1.9.2.2 installed over Ubuntu 14.04 LTS + nginx with naxsi + hhvm + basic firewall and fail2ban config. And on the other server Odoo 8 installed over Ubuntu 14.04 LTS with basic firewall config. All hosted at Linode.com virtual servers.
Magento Odoo Connector installed following thig guide: http://odoo-magento-connector.com/guides/installation_guide.html#installation
SOAP/XML-RPC - Users and Role just like in the guide.

When doing Metadata synchronization i always get Fault 2 error Access Denied:
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 952, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 940, in _call_kw
    return checked_call(request.db, _args, *_kwargs)
  File "/opt/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 939, in checked_call
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 363, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo-magento/connector-magento/magentoerpconnect/magento_model.py", line 198, in synchronize_metadata
    import_batch(session, model, backend.id)
  File "/opt/odoo-magento/connector-magento/magentoerpconnect/unit/import_synchronizer.py", line 379, in import_batch
    importer.run(filters=filters)
  File "/opt/odoo-magento/connector-magento/magentoerpconnect/unit/import_synchronizer.py", line 248, in run
    record_ids = self.backend_adapter.search(filters)
  File "/opt/odoo-magento/connector-magento/magentoerpconnect/unit/backend_adapter.py", line 211, in search
    [filters] if filters else [{}])
  File "/opt/odoo-magento/connector-magento/magentoerpconnect/unit/backend_adapter.py", line 159, in _call
    full_url=custom_url) as api:
  File "/usr/local/lib/python2.7/dist-packages/magento/api.py", line 136, in __enter__
    self.username, self.password)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in **call**
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1306, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1482, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 794, in close
    raise Fault(**self._stack[0])
Fault: Fault 2: Access denied.

Please, can anybody help me with that?

**Comment by Ivanio** [comment]
Just tryed with OpenERP 7.0 installation, the same happens. Maybe the problem is with magento server configuration? Generally magento is working perfect all its futures only problem is with xmlrpc connection with Odoo

**Comment by Ivanio** [comment]
Finally found a solution for me. Changed the nginx configuration back to php5-fpm from hhvm and it works. Seems there are some problem between xml-rpc and hhvm. But i can't see it.
