### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by 394879024** [OCA/connector-magento#204]
hi，I install to version odoo8，But the following error occurred：
2016-03-25 13:24:22,193 10432 ERROR odoo openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "F:/new_info/odoo/source/svn_openerp-7.0/code/openerp/trunk/odoo\openerp\http.py", line 500, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "F:/new_info/odoo/source/svn_openerp-7.0/code/openerp/trunk/odoo\openerp\http.py", line 517, in dispatch
    result = self._call_function(*_self.params)
  File "F:/new_info/odoo/source/svn_openerp-7.0/code/openerp/trunk/odoo\openerp\http.py", line 283, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "F:/new_info/odoo/source/svn_openerp-7.0/code/openerp/trunk/odoo\openerp\service\model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "F:/new_info/odoo/source/svn_openerp-7.0/code/openerp/trunk/odoo\openerp\http.py", line 280, in checked_call
    return self.endpoint(_a, *_kw)
  File "F:/new_info/odoo/source/svn_openerp-7.0/code/openerp/trunk/odoo\openerp\http.py", line 733, in __call__
    return self.method(_args, *_kw)
  File "F:/new_info/odoo/source/svn_openerp-7.0/code/openerp/trunk/odoo\openerp\http.py", line 376, in response_wrap
    response = f(_args, *_kw)
  File "F:\new_info\odoo\source\svn_openerp-7.0\code\openerp\trunk\odoo\addons\web\controllers\main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "F:\new_info\odoo\source\svn_openerp-7.0\code\openerp\trunk\odoo\addons\web\controllers\main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "F:/new_info/odoo/source/svn_openerp-7.0/code/openerp/trunk/odoo\openerp\api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "F:\new_info\odoo\source\svn_openerp-7.0\code\openerp\trunk\odoo\openerp\addons\base\module\module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "F:/new_info/odoo/source/svn_openerp-7.0/code/openerp/trunk/odoo\openerp\api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "F:\new_info\odoo\source\svn_openerp-7.0\code\openerp\trunk\odoo\openerp\addons\base\module\module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "F:/new_info/odoo/source/svn_openerp-7.0/code/openerp/trunk/odoo\openerp\modules\registry.py", line 324, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "F:/new_info/odoo/source/svn_openerp-7.0/code/openerp/trunk/odoo\openerp\modules\loading.py", line 358, in load_modules
    loaded_modules, update_module)
  File "F:/new_info/odoo/source/svn_openerp-7.0/code/openerp/trunk/odoo\openerp\modules\loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "F:/new_info/odoo/source/svn_openerp-7.0/code/openerp/trunk/odoo\openerp\modules\loading.py", line 162, in load_module_graph
    registry.setup_models(cr, partial=True)
  File "F:/new_info/odoo/source/svn_openerp-7.0/code/openerp/trunk/odoo\openerp\modules\registry.py", line 167, in setup_models
    model._setup_fields(cr, SUPERUSER_ID, partial=partial)
  File "F:/new_info/odoo/source/svn_openerp-7.0/code/openerp/trunk/odoo\openerp\api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "F:/new_info/odoo/source/svn_openerp-7.0/code/openerp/trunk/odoo\openerp\api.py", line 332, in old_api
    result = method(recs, _args, *_kwargs)
  File "F:/new_info/odoo/source/svn_openerp-7.0/code/openerp/trunk/odoo\openerp\models.py", line 2981, in _setup_fields
    field.setup(self.env)
  File "F:/new_info/odoo/source/svn_openerp-7.0/code/openerp/trunk/odoo\openerp\fields.py", line 398, in setup
    self._setup(env)
  File "F:/new_info/odoo/source/svn_openerp-7.0/code/openerp/trunk/odoo\openerp\fields.py", line 1352, in _setup
    super(_Relational, self)._setup(env)
  File "F:/new_info/odoo/source/svn_openerp-7.0/code/openerp/trunk/odoo\openerp\fields.py", line 403, in _setup
    self._setup_related(env)
  File "F:/new_info/odoo/source/svn_openerp-7.0/code/openerp/trunk/odoo\openerp\fields.py", line 434, in _setup_related
    recs = recs[name]
  File "F:/new_info/odoo/source/svn_openerp-7.0/code/openerp/trunk/odoo\openerp\models.py", line 5437, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "F:/new_info/odoo/source/svn_openerp-7.0/code/openerp/trunk/odoo\openerp\fields.py", line 741, in **get**
    return self.null(record.env)
  File "F:/new_info/odoo/source/svn_openerp-7.0/code/openerp/trunk/odoo\openerp\fields.py", line 1378, in null
    return env[self.comodel_name]
  File "F:/new_info/odoo/source/svn_openerp-7.0/code/openerp/trunk/odoo\openerp\api.py", line 727, in **getitem**
    return self.registry[model_name]._browse(self, ())
  File "F:/new_info/odoo/source/svn_openerp-7.0/code/openerp/trunk/odoo\openerp\modules\registry.py", line 100, in __getitem__
    return self.models[model_name]
KeyError: None
2016-03-25 13:24:22,224 10432 INFO odoo openerp.modules.loading: loading 1 modules...

Could help me see where the error occurred

**Comment by JayVora-SerpentCS** [comment]
It seems you downloaded v8, and using it with the source ocde of v7.
