### ISSUE TITLE
Product import

### ISSUE THREAD

**Issue by gfcapalbo** [OCA/connector-magento#206]
Hello, 

I have a working odoo connector, running with jobrunner where 3 channels are assigned to root and specifically 2 channels are assigned to root.magento

When running jobs everything goes well. Except for some products, the job remains stuck on start and my logs says:

2016-04-05 10:02:29,596 10345 ERROR junglegym openerp.addons.connector.controllers.main: Traceback (most recent call last):
  File "/home/odojngprd80/odoo/parts/connector/connector/controllers/main.py", line 90, in runjob
    self._try_perform_job(session_hdl, job)
  File "/home/odojngprd80/odoo/parts/connector/connector/controllers/main.py", line 66, in _try_perform_job
    job.perform(session)
  File "/home/odojngprd80/odoo/parts/connector/connector/queue/job.py", line 511, in perform
    self.result = self.func(session, _self.args, *_self.kwargs)
  File "/home/odojngprd80/odoo/parts/connector-magento/magentoerpconnect/unit/import_synchronizer.py", line 391, in import_record
    importer.run(magento_id, force=force)
  File "/home/odojngprd80/odoo/parts/connector-magento/magentoerpconnect/unit/import_synchronizer.py", line 233, in run
    binding = self._create(record)
  File "/home/odojngprd80/odoo/parts/connector-magento/magentoerpconnect/product.py", line 571, in _create
    openerp_binding = super(ProductImporter, self)._create(data)
  File "/home/odojngprd80/odoo/parts/connector-magento/magentoerpconnect/unit/import_synchronizer.py", line 169, in _create
    self._validate_data(data)
  File "/home/odojngprd80/odoo/parts/connector-magento/magentoerpconnect/product.py", line 568, in _validate_data
    self._validate_product_type(data)
  File "/home/odojngprd80/odoo/parts/connector-magento/magentoerpconnect/product.py", line 541, in _validate_product_type
    product_type)
InvalidDataError: The product type 'bundle' is not yet supported in the connector.

I understand that unsupported types are not there , but why isn't the job put in "FAILED" , but remains stuck forever in started?

I run the import manually from the connector backend and the connector is pretty much stock no particular customizations.

Any ideas?

**Comment by gfcapalbo** [comment]
Solved by  https://github.com/OCA/connector/pull/186/files, please review.
