### ISSUE TITLE
[8.0] Wrong automatic payment of sale order after import 

### ISSUE THREAD

**Issue by haroldtamo** [OCA/connector-magento#208]
Impacted versions: 8.0

Steps to reproduce:

*Create an automatic workflow (Sales>Configuration>Sale>automatic workflow) :
 -shipping policy: Deliver all products at once
-Invoice Policy: On Demand
-Invoice on : Ordered Quantities
-Validate Order: checked (leave all other checkboxes unchecked)
-Create Invoice: No automatic invoice
- Create a payment method with the previous automatic workflow
- Make an order on magento with the previous payment method and wait import on Odoo.

Current behavior:
After import, an account move is generated for the order and a button(View Automatic Payment) is added on Sale order form.

*_The problem is since the invoice was not created yet, when we create it and validate, another payment is created which make us ends up with two payment for the same order.
*_
Is it a configuration matter ?

Expected behavior:

A payment should not be created after import since we explicitely refuse to create an invoice on the automatic worflow configuration (Create Invoice: No automatic invoice)

Video/Screenshot link (optional):

**Comment by guewen** [comment]
> A payment should not be created after import since we explicitely refuse to create an invoice on the automatic worflow configuration (Create Invoice: No automatic invoice)

Creation of the invoice and payments are unrelated.

> when we create it and validate, another payment is created which make us ends up with two payment for the same order.

Why? An invoice does not automatically create payments AFAIK?

Finally, if you don't want the connector to create payments when the order is imported, you have to remove the journal from the payment method (the tooltip explains that)

**Comment by haroldtamo** [comment]
> Creation of the invoice and payments are unrelated.

What i do not understand is what is the use case of create a payment when the order is not even confirmed. For the order to reach the "closed" state, we need to create an invoice and when we will do so, we will also need to register a payment which will create a duplicate. Or am I missing something ?

> Why? An invoice does not automatically create payments AFAIK?

Indeed but we need to register payment in order to mark the invoice as paid and close the order. When we do so, another payment is created.

> Finally, if you don't want the connector to create payments when the order is imported, you have to remove the journal from the payment method (the tooltip explains that)

My bad, I didn't notice that. Thanks!

**Comment by guewen** [comment]
> What i do not understand is what is the use case of create a payment when the order is not even confirmed. For the order to reach the "closed" state, we need to create an invoice and when we will do so, we will also need to register a payment which will create a duplicate. Or am I missing something ?
> 
> Indeed but we need to register payment in order to mark the invoice as paid and close the order. When we do so, another payment is created.

The order has been confirmed and paid on Magento, that's why a payment is generated on Odoo.
And no, in that case you won't register a payment on the invoice, but you'll reconcile the existing payment with the invoice's move lines (reconciled automatically if you have [sale_payment_method_automatic_workflow).](https://github.com/OCA/sale-workflow/tree/8.0/sale_payment_method_automatic_workflow), once the payment and the move lines are reconciled, the invoice will be marked as paid and the order will be done.

**Comment by haroldtamo** [comment]
sale_payment_method_automatic_workflow is installed and the automatic workflow job activated but the move lines and payment aren't reconciled.
I found some order import jobs failed. the error is  in sale_payment_method and it looks like an user rights problem(although orders are imported by admin user) (see error logs below). I think it is related with the original problem and I'm trying to debug but please, let me know if you have any idea. Thanks!

http://pastebin.com/58vpZ4bA

Traceback (most recent call last):
  File "/opt/odoo/magerpdependencies/connector/connector/queue/worker.py", line 124, in run_job
    job.perform(session)
  File "/opt/odoo/magerpdependencies/connector/connector/queue/job.py", line 467, in perform
    self.result = self.func(session, _self.args, *_self.kwargs)
  File "/opt/odoo/magerpdependencies/connector-magento/magentoerpconnect/unit/import_synchronizer.py", line 379, in import_record
    importer.run(magento_id, force=force)
  File "/opt/odoo/magerpdependencies/connector-magento/magentoerpconnect/unit/import_synchronizer.py", line 225, in run
    self._after_import(binding)
  File "/opt/odoo/magerpdependencies/connector-magento/magentoerpconnect/sale.py", line 746, in _after_import
    self._create_payment(binding)
  File "/opt/odoo/magerpdependencies/connector-magento/magentoerpconnect/sale.py", line 710, in _create_payment
    binding.openerp_id.automatic_payment(amount)
  File "/opt/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/magerpdependencies/e-commerce/sale_payment_method/sale.py", line 107, in automatic_payment
    self._add_payment(journal, amount, date)
  File "/opt/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/magerpdependencies/e-commerce/sale_payment_method/sale.py", line 136, in _add_payment
    move_model.create(move_vals)
  File "/opt/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 464, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/opt/odoo/openerp/addons/account/account.py", line 1384, in create
    result = super(account_move, self).create(cr, uid, vals, c)
  File "/opt/odoo/openerp/api.py", line 237, ·in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 332, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/magerpdependencies/connector/connector/producer.py", line 48, in create
    record_id = create_original(self, vals)
  File "/opt/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 3968, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 464, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 4153, in _create
    result += self._columns[field].set(cr, self, id_new, field, vals[field], user, rel_context) or []
  File "/opt/odoo/openerp/osv/fields.py", line 742, in set
    id_new = obj.create(cr, user, act[2], context=context)
  File "/opt/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/addons/account/account_move_line.py", line 1257, in create
    if ('account_id' in vals) and not account_obj.read(cr, uid, [vals['account_id']], ['active'])[0]['active']:
  File "/opt/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 3080, in read
    result = BaseModel.read(records, fields, load=load)
  File "/opt/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 3123, in read
    values[name] = field.convert_to_read(record[name], use_name_get)
  File "/opt/odoo/openerp/models.py", line 5443, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/openerp/fields.py", line 746, in **get**
    return record._cache[self]
  File "/opt/odoo/openerp/models.py", line 5777, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "/opt/odoo/openerp/fields.py", line 53, in get
    raise self.exception
AccessError: ('AccessError', 'The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: account.account, Operation: read)')

**Comment by haroldtamo** [comment]
It wasn't an acces rights error.  the partner on order did not have the property_account_receivable field set which is weird since it's a mandatory field. the problem come from the import of partners. filling the property_account_receivable field on the partner fix the issue.
Thanks again for your kind support.

**Comment by guewen** [comment]
Glad that you found out the issue :)
