### ISSUE TITLE
Pulled all, have some errors, not others

### ISSUE THREAD

**Issue by l-arnold** [OCA/connector-magento#232]
Ran full set of GitPull yesterday.  Was able to bring in a few orders which were not syncronizing prior.
The Only Directory I did not Update in my Git Pull Exercize was the "openlabs-magento" directory as I expected it was not updated (perhaps I am wrong).

Using Branch 8 for All.

I just Updated Backend Products from Connector.

Several Products Came through that were defined as "Simple"
Unfortunately, several simple products that were created from Configurable Products in Magento returned the following Error.  Not at all clear why.  These have always imported in the past.

> Traceback (most recent call last):
>   File "/opt/openerp/oca/connector/connector/controllers/main.py", line 90, in runjob
>     self._try_perform_job(session_hdl, job)
>   File "/opt/openerp/oca/connector/connector/controllers/main.py", line 66, in _try_perform_job
>     job.perform(session)
>   File "/opt/openerp/oca/connector/connector/queue/job.py", line 512, in perform
>     self.result = self.func(session, _self.args, *_self.kwargs)
>   File "/opt/openerp/oca/connector-magento/magentoerpconnect/unit/import_synchronizer.py", line 391, in import_record
>     importer.run(magento_id, force=force)
>   File "/opt/openerp/oca/connector-magento/magentoerpconnect/unit/import_synchronizer.py", line 204, in run
>     self.magento_record = self._get_magento_data()
>   File "/opt/openerp/oca/connector-magento/magentoerpconnect/unit/import_synchronizer.py", line 61, in _get_magento_data
>     return self.backend_adapter.read(self.magento_id)
>   File "/opt/openerp/oca/connector-magento/magentoerpconnect/product.py", line 245, in read
>     [int(id), storeview_id, attributes, 'id'])
>   File "/opt/openerp/oca/connector-magento/magentoerpconnect/product.py", line 210, in _call
>     return super(ProductProductAdapter, self)._call(method, arguments)
>   File "/opt/openerp/oca/connector-magento/magentoerpconnect/unit/backend_adapter.py", line 168, in _call
>     result = api.call(method, arguments)
>   File "/usr/local/lib/python2.7/dist-packages/magento-1.0-py2.7.egg/magento/api.py", line 159, in call
>     return self.client.call(self.session, resource_path, arguments)
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
>     return self.__send(self.__name, args)
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1591, in __request
>     verbose=self.__verbose
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
>     return self.single_request(host, handler, request_body, verbose)
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1306, in single_request
>     return self.parse_response(response)
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1476, in parse_response
>     p.feed(data)
>   File "/usr/lib/python2.7/xmlrpclib.py", line 558, in feed
>     self._parser.Parse(data, 0)
> ExpatError: not well-formed (invalid token): line 2, column 1067

**Comment by l-arnold** [comment]
5 x errors:  Last lines of each are:

ExpatError: not well-formed (invalid token): line 9, column 111
ExpatError: not well-formed (invalid token): line 2, column 1063
ExpatError: not well-formed (invalid token): line 2, column 1067
ExpatError: not well-formed (invalid token): line 2, column 1065
ExpatError: not well-formed (invalid token): line 2, column 1063

**Comment by l-arnold** [comment]
Ran a Restore to Prior to the GitPull.  Imported new products.  Same Error.

Seems to be some issue with the Database structure in Magento on certain attribute types which have always worked in the past.

Will run with the current "pull".  Did update openlabs-magento, but there were no changes there.

**Comment by l-arnold** [comment]
Looking a bit at the following.  Will see if I can clean the product entries a bit:  
https://bugs.launchpad.net/openerp-connector-magento/+bug/1302483

**Comment by l-arnold** [comment]
Yesterday I tried, unsuccessfully, to import some products into Magento (7 products).  They never showed up in Magento.  Some methods showed success.  Others did not.  Perhaps this is related also.

I sill restart Magento and try a new import in Odoo before anything else.  

Does anyone have experience with data issues from Magento Imports?  Again, nothing shows up in Catalog.Product.Entity or Magento Products list from the imports.

**Comment by l-arnold** [comment]
Massaged the 3 Main culprets...  has to do with "outlier" formatting coming in.  I found the best way to find it is actually to view the data in via an ODBC connection in FileMaker Pro.  Will work on some other methods.
This is likely why the imports did not work yesterday but I am not clear on that one.
