### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'bool' and 'str'`  magentoerpconnect 8.0.3.0.0.99.dev90

### ISSUE THREAD

**Issue by ghost** [OCA/connector-magento#253]
Greetings, I have a fresh install of odoo 8 and I downloaded and installed Magentoerpconnect 8.0.3.0.0.99.dev90 using python wheel. I am unfamiliar with odoo as this is my first time using it; however, upon installation of this package I received a server error when I clicked on Connector > Checkpoint > Form View. The error can be seen in the code below. I pray for the Lord's help in resolving this matter. God bless you!

```Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/models.py", line 5955, in onchange
    value = record[name]
  File "/usr/lib/python2.7/site-packages/openerp/models.py", line 5657, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python2.7/site-packages/openerp/fields.py", line 838, in __get__
    self.determine_draft_value(record)
  File "/usr/lib/python2.7/site-packages/openerp/fields.py", line 946, in determine_draft_value
    self._compute_value(record)
  File "/usr/lib/python2.7/site-packages/openerp/fields.py", line 885, in _compute_value
    self.compute(records)
  File "/usr/lib/python2.7/site-packages/odoo_addons/connector/checkpoint/checkpoint.py", line 51, in _compute_record
    check.record = check.model_id.model + ',' + str(check.record_id)
TypeError: unsupported operand type(s) for +: 'bool' and 'str'`

**Comment by guewen** [comment]
It seems that the checkpoint is not linked to any `model`, which is unexpected. Can you give the git sha / tag of the `connecto` and `connector-magento` repositories you use?

**Comment by ghost** [comment]
Thanks guewen, I initially wanted to get the PR 200 but as I read I was able to install the connector via python wheel here. https://pypi.python.org/pypi/odoo8-addon-magentoerpconnect/8.0.3.0.0.99.dev90 

odoo8_addon_magentoerpconnect-8.0.3.0.0.99.dev90-py2-none-any.whl (md5)	Python Wheel	py2	2017-05-20	3MB

I am not sure of the git sha / tag. God bless you!

**Comment by ghost** [comment]
Upgraded to latest wheel and it still shows error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 546, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 583, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 319, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 316, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 812, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 412, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/models.py", line 5955, in onchange
    value = record[name]
  File "/usr/lib/python2.7/site-packages/openerp/models.py", line 5657, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python2.7/site-packages/openerp/fields.py", line 838, in __get__
    self.determine_draft_value(record)
  File "/usr/lib/python2.7/site-packages/openerp/fields.py", line 946, in determine_draft_value
    self._compute_value(record)
  File "/usr/lib/python2.7/site-packages/openerp/fields.py", line 885, in _compute_value
    self.compute(records)
  File "/usr/lib/python2.7/site-packages/odoo_addons/connector/checkpoint/checkpoint.py", line 51, in _compute_record
    check.record = check.model_id.model + ',' + str(check.record_id)
TypeError: unsupported operand type(s) for +: 'bool' and 'str'

**Comment by guewen** [comment]
You should check in database if you have a `connector_checkpoint` record with an empty `model_id`, and delete it.

**Comment by ghost** [comment]
Thanks!
