### ISSUE TITLE
Odoo error;  NameError: name 'cachedmethod' is not defined

### ISSUE THREAD

**Issue by bleijenbergjochem** [OCA/connector-magento#277]
Hi,
Odoo 10 is throwing the following error below afther a fresh install on ubuntu;
I tried: pip install cached-property but no solution.

2018-04-20 06:45:45,910 1069 INFO ? odoo.addons.report.models.report: Will use the Wkhtmltopdf binary at /usr/bin/wkhtmltopdf
2018-04-20 06:45:46,653 1069 INFO ? werkzeug: 86.93.83.96 - - [20/Apr/2018 06:45:46] "GET / HTTP/1.1" 500 -
2018-04-20 06:45:46,663 1069 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 180, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 168, in execute
    application_iter = app(environ, start_response)
  File "/odoo/odoo-server/odoo/service/server.py", line 246, in app
    return self.app(e, s)
  File "/odoo/odoo-server/odoo/service/wsgi_server.py", line 186, in application
    return application_unproxied(environ, start_response)
  File "/odoo/odoo-server/odoo/service/wsgi_server.py", line 172, in application_unproxied
    result = handler(environ, start_response)
  File "/odoo/odoo-server/odoo/http.py", line 1322, in __call__
    self.load_addons()
  File "/odoo/odoo-server/odoo/http.py", line 1343, in load_addons
    m = __import__('odoo.addons.' + module)
  File "/odoo/odoo-server/odoo/modules/module.py", line 81, in load_module
    execfile(modfile, new_mod.__dict__)
  File "/odoo/custom/addons/connector/connector/__init__.py", line 2, in <module>
    from . import components
  File "/odoo/custom/addons/connector/connector/components/__init__.py", line 2, in <module>
    from . import core
  File "/odoo/custom/addons/connector/connector/components/core.py", line 68, in <module>
    from odoo.addons.component.core import AbstractComponent
  File "/odoo/odoo-server/odoo/modules/module.py", line 81, in load_module
    execfile(modfile, new_mod.__dict__)
  File "/odoo/custom/addons/connector/component/__init__.py", line 2, in <module>
    from . import core
  File "/odoo/custom/addons/connector/component/core.py", line 65, in <module>
    class ComponentRegistry(object):
  File "/odoo/custom/addons/connector/component/core.py", line 106, in ComponentRegistry
    @cachedmethod(operator.attrgetter('_cache'))
NameError: name 'cachedmethod' is not defined

**Comment by l-arnold** [comment]
RE wkhtmltopdf 
Back in Version 8 installing wkhtmltopdf took some work. We got it into the Turnkeylinux.org build. 
Reference to that is here, though, to be honest, it seemed there was more we needed to also install. 
#adjust these as suits your setup. They work as is for 64bit v13.0 TKL
ARCH=amd64
REL=wheezy
VER=0.12.2.1

wget http://downloads.sourceforge.net/project/wkhtmltopdf/${VER}/wkhtmltox-${VER}_linux-${REL}-${ARCH}.deb
deb -i --force-depends wkhtmltox-*.deb

apt-get -y -f install 
You may have it installed however and just not have enough Memory on your server. My expereince when we were setting this is that I needed to bump server resources enough to get the PDF's to generate. 

I think we will be diving in to version 10 Odoo on a TKL build soon. 

This is a link to the full 8.0 build that has wkhtmltopdf (wkhtmltox) built in. 
https://www.turnkeylinux.org/blog/community-built-odoo-appliance 

Perhaps this is helpful. 
Best regards and good luck. 

Landis Arnold 
Nomadic, Inc.

**Comment by bleijenbergjochem** [comment]
I solved the problem by using odoo 8 with the magento-connector. It will also suit my needs .
