### ISSUE TITLE
 NotReadableJobError: ('Could not unpickle.', 'False') 

### ISSUE THREAD

**Issue by atuljain** [OCA/connector-magento#30]
Hello,
I installed magento connector and it was working fine but unfortunatly my customer update it connector module from Apps Menu ,
Now i am getting no handler error but when i go back and look my log file then i got the error

Client Traceback (most recent call last):
  File "/opt/openerp/server/openerp/addons/web/http.py", line 204, in dispatch
    response["result"] = method(self, *_self.params)
  File "/opt/openerp/server/openerp/addons/web/controllers/main.py", line 1132, in call_button
    action = self._call_kw(req, model, method, args, {})
  File "/opt/openerp/server/openerp/addons/web/controllers/main.py", line 1120, in _call_kw
    return getattr(req.session.model(model), method)(_args, **kwargs)
  File "/opt/openerp/server/openerp/addons/web/session.py", line 42, in proxy
    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
  File "/opt/openerp/server/openerp/addons/web/session.py", line 30, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/opt/openerp/server/openerp/addons/web/session.py", line 103, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)

Server Traceback (most recent call last):
  File "/opt/openerp/server/openerp/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/opt/openerp/server/openerp/netsvc.py", line 296, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/openerp/server/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/opt/openerp/server/openerp/osv/osv.py", line 190, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/opt/openerp/server/openerp/osv/osv.py", line 132, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/opt/openerp/server/openerp/osv/osv.py", line 199, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/opt/openerp/server/openerp/osv/osv.py", line 187, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/opt/openerp/magento_addons/openerp-connector/connector/queue/model.py", line 393, in requeue
    self.pool.get('queue.job').requeue(cr, uid, job_ids, context=context)
  File "/opt/openerp/magento_addons/openerp-connector/connector/queue/model.py", line 127, in requeue
    self._change_job_state(cr, uid, ids, PENDING, context=context)
  File "/opt/openerp/magento_addons/openerp-connector/connector/queue/model.py", line 110, in _change_job_state
    job = storage.load(job.uuid)
  File "/opt/openerp/magento_addons/openerp-connector/connector/queue/job.py", line 246, in load
    func = _unpickle(str(stored.func))
  File "/opt/openerp/magento_addons/openerp-connector/connector/queue/job.py", line 71, in _unpickle
    raise NotReadableJobError('Could not unpickle.', pickled)
NotReadableJobError: ('Could not unpickle.', 'False')

For avoiding this error i also follow some patched which is provided by other's contributor

https://code.launchpad.net/~camptocamp/openerp-connector/7.0-unicode-pickled-1288187/+merge/209481

also follow this

https://code.launchpad.net/~acsone-openerp/openerp-connector/bug-1288187-sbi-unicode/+merge/209430

please any one can help me

**Comment by guewen** [comment]
Hi,

If your customer updated the module from the Apps menu, it means that it installed an old version.
You must remove the module that has been installed by Apps. I guess it is located in `server/openerp/addons`. Still having the correct addons in another addons path does not mean it should work, because the one installed by Apps shadows the good one. The first thing is to clean you environment by removing the modules installed by Apps.

Then, it sounds like a job has no `func`, search for records in `queue_job` in the database with an empty `func` and if you have some, remove them.

Also, the patch 209481 has been merged so you don't have to apply it. The patch 209430 should not be applied (replaced by 209481).
