### ISSUE TITLE
Openerp7 -wsgi cannot import name related_action

### ISSUE THREAD

**Issue by eyes2design** [OCA/connector-magento#31]
2014-08-29 17:06:22,505 8192 CRITICAL ? openerp.modules.module: Couldn't load module web
2014-08-29 17:06:22,506 8192 CRITICAL ? openerp.modules.module: cannot import name related_action
2014-08-29 17:06:22,506 8192 ERROR ? openerp.service: Failed to load server-wide module `web`.
The `web` module is provided by the addons found in the `openerp-web` project.
Maybe you forgot to add those addons in your addons_path configuration.
Traceback (most recent call last):
  File "/www/openerp/openerp/odoo/openerp/service/**init**.py", line 60, in load_server_wide_modules
    openerp.modules.module.load_openerp_module(m)
  File "/www/openerp/openerp/odoo/openerp/modules/module.py", line 415, in load_openerp_module
    getattr(sys.modules['openerp.addons.' + module_name], info['post_load'])()
  File "/www/openerp/openerp/odoo/addons/web/http.py", line 628, in wsgi_postload
    openerp.wsgi.register_wsgi_handler(Root())
  File "/www/openerp/openerp/odoo/addons/web/http.py", line 517, in **init**
    self.load_addons()
  File "/www/openerp/openerp/odoo/addons/web/http.py", line 580, in load_addons
    m = **import**('openerp.addons.' + module)
  File "/www/openerp/openerp/odoo/openerp/modules/module.py", line 133, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/www/openerp/openerp/odoo/oca_connector/connector-magento/magentoerpconnect/**init**.py", line 6, in <module>
    import magento_model
  File "/www/openerp/openerp/odoo/oca_connector/connector-magento/magentoerpconnect/magento_model.py", line 34, in <module>
    from .unit.backend_adapter import GenericAdapter
  File "/www/openerp/openerp/odoo/oca_connector/connector-magento/magentoerpconnect/unit/**init**.py", line 5, in <module>
    import import_synchronizer
  File "/www/openerp/openerp/odoo/oca_connector/connector-magento/magentoerpconnect/unit/import_synchronizer.py", line 26, in <module>
    from openerp.addons.connector.queue.job import job, related_action
ImportError: cannot import name related_action

**Comment by guewen** [comment]
Hi,
this error  means that you do not use the last version of the connector.
