### ISSUE TITLE
odoo 11/12 - magento 1.9.x magento.product.category error

### ISSUE THREAD

**Issue by mbattistini** [OCA/connector-magento#325]
hi all,

using the old module for magento:

bzr branch lp:magentoerpconnect/magento-module-oerp6.x-stable magento-module

synchronized initial metadata without problem.

Then with product category:

2021-05-31 14:48:09,332 8766 WARNING ? odoo.addons.queue_job.jobrunner.channels: unknown channel root.magento, using root channel for job 2640f048-0a4c-46bd-89aa-60c9fc17b758
2021-05-31 14:48:09,332 8766 INFO ? odoo.addons.queue_job.jobrunner.runner: asking Odoo to run job 2640f048-0a4c-46bd-89aa-60c9fc17b758 on db DATABASE
2021-05-31 14:48:09,339 8766 WARNING ? odoo.addons.queue_job.jobrunner.channels: unknown channel root.magento, using root channel for job 2640f048-0a4c-46bd-89aa-60c9fc17b758
2021-05-31 14:48:09,353 8766 WARNING ? odoo.addons.queue_job.jobrunner.channels: unknown channel root.magento, using root channel for job 2640f048-0a4c-46bd-89aa-60c9fc17b758
2021-05-31 14:48:09,361 8753 INFO DATABASE werkzeug: 192.168.47.1 - - [31/May/2021 14:48:09] "POST /web/dataset/call_kw/magento.backend/read HTTP/1.0" 200 - 7 0.004 0.009
2021-05-31 14:48:09,400 8754 INFO DATABASE werkzeug: 192.168.47.1 - - [31/May/2021 14:48:09] "POST /web/dataset/call_kw/magento.website/read HTTP/1.0" 200 - 3 0.002 0.007
2021-05-31 14:48:09,772 8759 ERROR DATABASE odoo.addons.queue_job.controllers.main: Traceback (most recent call last):
  File "/opt/odoo_addons_12/queue/queue_job/controllers/main.py", line 85, in runjob
    self._try_perform_job(env, job)
  File "/opt/odoo_addons_12/queue/queue_job/controllers/main.py", line 32, in _try_perform_job
    job.perform()
  File "/opt/odoo_addons_12/queue/queue_job/job.py", line 465, in perform
    self.result = self.func(*tuple(self.args), **self.kwargs)
  File "/opt/odoo_addons_12/connector-magento/connector_magento/models/magento_binding/common.py", line 42, in import_batch
    return importer.run(filters=filters)
  File "/opt/odoo_addons_12/connector-magento/connector_magento/models/product_category/importer.py", line 56, in run
    tree = self.backend_adapter.tree()
  File "/opt/odoo_addons_12/connector-magento/connector_magento/models/product_category/common.py", line 125, in tree
    return filter_ids(tree)
UnboundLocalError: local variable 'tree' referenced before assignment

2021-05-31 14:48:09,855 8766 WARNING ? odoo.addons.queue_job.jobrunner.channels: unknown channel root.magento, using root channel for job 2640f048-0a4c-46bd-89aa-60c9fc17b758
2021-05-31 14:48:09,893 8759 INFO DATABASE werkzeug: 127.0.0.1 - - [31/May/2021 14:48:09] "GET /queue_job/runjob?db=DATABASE&job_uuid=2640f048-0a4c-46bd-89aa-60c9fc17b758 HTTP/1.1" 500 - 92 0.059 0.495
2021-05-31 14:48:09,895 8766 ERROR ? odoo.addons.queue_job.jobrunner.runner: exception in GET http://127.0.0.1:8069/queue_job/runjob?db=DATABASE&job_uuid=2640f048-0a4c-46bd-89aa-60c9fc17b758
Traceback (most recent call last):
  File "/opt/odoo_addons_12/queue/queue_job/jobrunner/runner.py", line 251, in urlopen
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:8069/queue_job/runjob?db=DATABASE&job_uuid=2640f048-0a4c-46bd-89aa-60c9fc17b758
2021-05-31 14:48:09,915 8759 ERROR DATABASE werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 306, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 294, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 142, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1320, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1293, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python3/dist-packages/werkzeug/middleware/shared_data.py", line 220, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1488, in dispatch
    result = ir_http._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_http.py", line 22, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/http_routing/models/ir_http.py", line 403, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/utm/models/ir_http.py", line 26, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 212, in _dispatch
    return cls._handle_exception(e)
  File "/usr/lib/python3/dist-packages/odoo/addons/utm/models/ir_http.py", line 31, in _handle_exception
    response = super(IrHttp, cls)._handle_exception(exc)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 182, in _handle_exception
    return request._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 776, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 208, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 835, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo_addons_12/queue/queue_job/controllers/main.py", line 85, in runjob
    self._try_perform_job(env, job)
  File "/opt/odoo_addons_12/queue/queue_job/controllers/main.py", line 32, in _try_perform_job
    job.perform()
  File "/opt/odoo_addons_12/queue/queue_job/job.py", line 465, in perform
    self.result = self.func(*tuple(self.args), **self.kwargs)
  File "/opt/odoo_addons_12/connector-magento/connector_magento/models/magento_binding/common.py", line 42, in import_batch
    return importer.run(filters=filters)
  File "/opt/odoo_addons_12/connector-magento/connector_magento/models/product_category/importer.py", line 56, in run
    tree = self.backend_adapter.tree()
  File "/opt/odoo_addons_12/connector-magento/connector_magento/models/product_category/common.py", line 125, in tree
    return filter_ids(tree)
UnboundLocalError: local variable 'tree' referenced before assignment - - -

It's been a while since I've been wasting my time without too much success, the only decent documentation is outdated at the link:

http://odoo-magento-connector.com/guides/installation_guide.html

Can anyone tell me what I'm doing wrong?

Thank you.

**Comment by pedrobaeza** [comment]
That branch is not suitable for that Odoo version, and there's no migration of the module for such versions.

**Comment by mbattistini** [comment]
sorry @pedrobaeza , do you mean there is no module to connect magento 1.9.x with odoo?

What can I use to stay FOSS?

Thanks.

**Comment by pedrobaeza** [comment]
Yeah, that's it. You can fund module developers to migrate/adapt the module to that Odoo and Magento versions.
