### ISSUE TITLE
magentoerpconnect_order_comment: nltk.clean_html() raises a NotImplementedError

### ISSUE THREAD

**Issue by guewen** [OCA/connector-magento#34]
magentoerpconnect_order_comment uses `nltk.clean_html(comment)` which does no longer work. It has been removed from the lib in version 3.0: https://github.com/nltk/nltk/commit/39a303e5ddc4cdb1a0b00a3be426239b1c24c8bb

From Travis:

```
2014-09-10 10:23:45,300 23456 TEST openerp_test openerp.modules.module: ERROR: test_20_export_sale_comment (openerp.addons.magentoerpconnect_order_comment.tests.test_synchronization.TestMagentoSaleCommentExport)

2014-09-10 10:23:45,300 23456 TEST openerp_test openerp.modules.module: ` Test export of sale order comment

2014-09-10 10:23:45,300 23456 TEST openerp_test openerp.modules.module: Traceback (most recent call last):

2014-09-10 10:23:45,300 23456 TEST openerp_test openerp.modules.module: ` File "/home/travis/build/OCA/connector-magento/magentoerpconnect_order_comment/tests/test_synchronization.py", line 154, in test_20_export_sale_comment

2014-09-10 10:23:45,300 23456 TEST openerp_test openerp.modules.module: ` export_record(self.session, 'magento.sale.comment', mag_comment_id)

2014-09-10 10:23:45,300 23456 TEST openerp_test openerp.modules.module: ` File "/home/travis/build/OCA/connector-magento/magentoerpconnect/unit/export_synchronizer.py", line 389, in export_record

2014-09-10 10:23:45,301 23456 TEST openerp_test openerp.modules.module: ` return exporter.run(binding_id, fields=fields)

2014-09-10 10:23:45,301 23456 TEST openerp_test openerp.modules.module: ` File "/home/travis/build/OCA/connector-magento/magentoerpconnect/unit/export_synchronizer.py", line 124, in run

2014-09-10 10:23:45,301 23456 TEST openerp_test openerp.modules.module: ` result = self._run(*args, **kwargs)

2014-09-10 10:23:45,301 23456 TEST openerp_test openerp.modules.module: ` File "/home/travis/build/OCA/connector-magento/magentoerpconnect/unit/export_synchronizer.py", line 375, in _run

2014-09-10 10:23:45,301 23456 TEST openerp_test openerp.modules.module: ` record = self._create_data(map_record, fields=fields)

2014-09-10 10:23:45,301 23456 TEST openerp_test openerp.modules.module: ` File "/home/travis/build/OCA/connector-magento/magentoerpconnect/unit/export_synchronizer.py", line 330, in _create_data

2014-09-10 10:23:45,301 23456 TEST openerp_test openerp.modules.module: ` return map_record.values(for_create=True, fields=fields, **kwargs)

2014-09-10 10:23:45,301 23456 TEST openerp_test openerp.modules.module: ` File "/home/travis/connector/connector/unit/mapper.py", line 904, in values

2014-09-10 10:23:45,301 23456 TEST openerp_test openerp.modules.module: ` values = self._mapper._apply(self, options=options)

2014-09-10 10:23:45,301 23456 TEST openerp_test openerp.modules.module: ` File "/home/travis/connector/connector/unit/mapper.py", line 643, in _apply

2014-09-10 10:23:45,301 23456 TEST openerp_test openerp.modules.module: ` return self._apply_with_options(map_record)

2014-09-10 10:23:45,301 23456 TEST openerp_test openerp.modules.module: ` File "/home/travis/connector/connector/unit/mapper.py", line 681, in _apply_with_options

2014-09-10 10:23:45,302 23456 TEST openerp_test openerp.modules.module: ` values = meth(map_record.source)

2014-09-10 10:23:45,302 23456 TEST openerp_test openerp.modules.module: ` File "/home/travis/build/OCA/connector-magento/magentoerpconnect_order_comment/sale.py", line 282, in comment

2014-09-10 10:23:45,302 23456 TEST openerp_test openerp.modules.module: ` return {'comment': nltk.clean_html(comment)}

2014-09-10 10:23:45,302 23456 TEST openerp_test openerp.modules.module: ` File "/usr/local/lib/python2.7/dist-packages/nltk/util.py", line 346, in clean_html

2014-09-10 10:23:45,302 23456 TEST openerp_test openerp.modules.module: ` raise NotImplementedError ("To remove HTML markup, use BeautifulSoup's get_text() function")

2014-09-10 10:23:45,302 23456 TEST openerp_test openerp.modules.module: ` NotImplementedError: To remove HTML markup, use BeautifulSoup's get_text() function
```

It should be replaced by BeautifulSoup or another library / own function that does the same thing.
Maybe we have to freeze the version of `nltk`, but it will be a problem some day.

**Comment by guewen** [comment]
@bealdav since you are the author, can you work on this bug please? The tests are red due to that.

**Comment by bealdav** [comment]
@guewen ok to fix.
I missed something and Odoo runs now on python 3 or what ? 
;-)

**Comment by guewen** [comment]
I meant version 3.0 of nltk

**Comment by bealdav** [comment]
I put
'external_dependencies': {
'python': ['beautifulsoup4'],
},

and if I do:
sudo pip install beautifulsoup4
it works in Ubuntu but fails with intregation continuous

What I missed ?

**Comment by bealdav** [comment]
It should be closed, I think ?
