### ISSUE TITLE
Import res.partner.category

### ISSUE THREAD

**Issue by kossovo** [OCA/connector-magento#48]
Tested on Odoo 7.0 and Magento 1.7.0.0 (with SAMPLE_DATA) 

Synchronization works well, the import of res.partner.category works, except for categories with a compound name (eg "TEST GROUP") 
I get the following traceback:

```
Traceback (most recent call last):
  File "/home/clovis/Documents/test/connector/connector/queue/worker.py", line 122, in run_job
    job.perform(session)
  File "/home/clovis/Documents/test/connector/connector/queue/job.py", line 491, in perform
    self.result = self.func(session, *self.args, **self.kwargs)
  File "/home/clovis/Documents/test/connector-magento/magentoerpconnect/unit/import_synchronizer.py", line 378, in import_record
    importer.run(magento_id, force=force)
  File "/home/clovis/Documents/test/connector-magento/magentoerpconnect/unit/import_synchronizer.py", line 232, in run
    self.binder.bind(self.magento_id, binding_id)
  File "/home/clovis/Documents/test/connector-magento/magentoerpconnect/unit/binder.py", line 125, in bind
    "got: %s, %s" % (external_id, binding_id)
AssertionError: external_id or binding_id missing, got: 0, 17
```

**Comment by dfrankland** [comment]
I am also running into this issue with OpenERP 7.0 and Magento ver. 1.8.1.0 and I get this traceback:

```
Traceback (most recent call last):
  File "/opt/openerp/addons/connector/connector/queue/worker.py", line 122, in run_job
    job.perform(session)
  File "/opt/openerp/addons/connector/connector/queue/job.py", line 491, in perform
    self.result = self.func(session, *self.args, **self.kwargs)
  File "/opt/openerp/addons/connector-magento/magentoerpconnect/unit/import_synchronizer.py", line 378, in import_record
    importer.run(magento_id, force=force)
  File "/opt/openerp/addons/connector-magento/magentoerpconnect/unit/import_synchronizer.py", line 232, in run
    self.binder.bind(self.magento_id, binding_id)
  File "/opt/openerp/addons/connector-magento/magentoerpconnect/unit/binder.py", line 125, in bind
    "got: %s, %s" % (external_id, binding_id)
AssertionError: external_id or binding_id missing, got: 0, 6
```

**Comment by guewen** [comment]
Hi,

Thanks for your reports.
I think I found a correction, could you test it and give your feedback on the pull request please? https://github.com/OCA/connector-magento/pull/61

**Comment by dfrankland** [comment]
I have pulled the changes, restarted the server, requeued all the jobs, and everything completed; works great!

Thanks again @guewen!
