### ISSUE TITLE
no handler found

### ISSUE THREAD

**Issue by sbarajas** [OCA/connector-magento#59]
Hello,
I have an Odoo 7 installation in a Debian 7 host, I have some addons installed: http://odoo-magento-connector.com/guides/installation_guide.html

$ bzr branch lp:openerp-connector/7.0 /opt/openerp-connector
$ bzr branch lp:openerp-connector-ecommerce/7.0 /opt/openerp-connector-ecommerce
$ bzr branch lp:openerp-connector-magento/7.0 /opt/openerp-connector-magento
$ bzr branch lp:e-commerce-addons/7.0 /opt/e-commerce-addons
$ bzr branch lp:openerp-product-attributes/7.0 /opt/openerp-product-attributes
$ bzr branch lp:sale-wkfl/7.0 /opt/sale-wkfl

My /etc/openerp/openerp-server.conf is like this:

[options]
; This is the password that allows database operations:
; admin_passwd = admin
db_host = False
db_port = False
db_user = openerp
db_password = False

addons_path = /opt/openerp-connector,/opt/openerp-connector-ecommerce,/opt/openerp-connector-magento,/opt/e-commerce-addons,/opt/openerp-product-attributes,/opt/sale-wkfl

When I updated to the last version of Odoo 7 (openerp_7.0-20141011-011008.deb):

apt-get update && apt-get upgrade

I got this:

root@OpenERP:~# sudo -u openerp openerp-server --config=/etc/openerp/openerp-server.conf --update=all
2014-10-11 17:20:12,474 2569 INFO ? openerp: OpenERP version 7.0-b42ae34
2014-10-11 17:20:12,475 2569 INFO ? openerp: addons paths: /opt/openerp-connector,/opt/openerp-connector-ecommerce,/opt/openerp-connector-magento,/opt/e-commerce-addons,/opt/openerp-product-attributes,/opt/sale-wkfl
2014-10-11 17:20:12,475 2569 INFO ? openerp: database hostname: localhost
2014-10-11 17:20:12,475 2569 INFO ? openerp: database port: 5432
2014-10-11 17:20:12,475 2569 INFO ? openerp: database user: openerp
2014-10-11 17:20:12,697 2569 CRITICAL ? openerp.modules.module: Couldn't load module web
2014-10-11 17:20:12,698 2569 CRITICAL ? openerp.modules.module: No module named magento
2014-10-11 17:20:12,698 2569 ERROR ? openerp.service: Failed to load server-wide module web.
The web module is provided by the addons found in the openerp-web project.
Maybe you forgot to add those addons in your addons_path configuration.
Traceback (most recent call last):
File "/usr/lib/python2.6/dist-packages/openerp/service/init.py", line 60, in load_server_wide_modules
openerp.modules.module.load_openerp_module(m)
File "/usr/lib/python2.6/dist-packages/openerp/modules/module.py", line 415, in load_openerp_module
getattr(sys.modules['openerp.addons.' + module_name], info['post_load'])()
File "/usr/lib/python2.6/dist-packages/openerp/addons/web/http.py", line 628, in wsgi_postload
openerp.wsgi.register_wsgi_handler(Root())
File "/usr/lib/python2.6/dist-packages/openerp/addons/web/http.py", line 517, in init
self.load_addons()
File "/usr/lib/python2.6/dist-packages/openerp/addons/web/http.py", line 580, in load_addons
m = import('openerp.addons.' + module)
File "/usr/lib/python2.6/dist-packages/openerp/modules/module.py", line 133, in load_module
mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
File "/opt/openerp-connector-magento/magentoerpconnect/init.py", line 6, in
import magento_model
File "/opt/openerp-connector-magento/magentoerpconnect/magento_model.py", line 34, in
from .unit.backend_adapter import GenericAdapter
File "/opt/openerp-connector-magento/magentoerpconnect/unit/init.py", line 5, in
import import_synchronizer
File "/opt/openerp-connector-magento/magentoerpconnect/unit/import_synchronizer.py", line 32, in
from ..related_action import link
File "/opt/openerp-connector-magento/magentoerpconnect/related_action.py", line 35, in
from .unit.backend_adapter import GenericAdapter
File "/opt/openerp-connector-magento/magentoerpconnect/unit/backend_adapter.py", line 26, in
import magento as magentolib
ImportError: No module named magento
2014-10-11 17:20:12,710 2569 INFO ? openerp.service.wsgi_server: HTTP service (werkzeug) running on 0.0.0.0:8069
2014-10-11 17:20:12,710 2569 INFO ? openerp: OpenERP server is running, waiting for connections...

And if I open the web page: http://127.0.0.1:8069, I can only see "no handler found"

**Comment by mistotebe** [comment]
Seems you might have either forgotten to install the `magento` package or installed it under your user only. Try installing it system-wide or for the `openerp` user.
