### ISSUE TITLE
Error when try to import product categories

### ISSUE THREAD

**Issue by plamarche** [OCA/connector-magento#73]
With the latest version of the connector with Magento 1.7.0.2 with php 5.4 and OpenERP v7 : 

For the task : openerp.addons.magentoerpconnect.unit.import_synchronizer.import_batch('magento.product.category', 1, filters={'from_date': datetime.datetime(2014, 12, 2, 19, 43, 11)})

I get this error message : 

```
Traceback (most recent call last): 
File "/opt/openerp7/git/connector/connector/queue/worker.py", line 122, in run_job job.perform(session) 
File "/opt/openerp7/git/connector/connector/queue/job.py", line 490, in perform self.result = self.func(session, *self.args, **self.kwargs) 
File "/opt/openerp7/git/connector-magento/magentoerpconnect/unit/import_synchronizer.py", line 369, in import_batch importer.run(filters=filters) 
File "/opt/openerp7/git/connector-magento/magentoerpconnect/product_category.py", line 184, in run tree = self.backend_adapter.tree() 
File "/opt/openerp7/git/connector-magento/magentoerpconnect/product_category.py", line 146, in tree [parent_id, storeview_id]) 
File "/opt/openerp7/git/connector-magento/magentoerpconnect/product_category.py", line 96, in _call return super(ProductCategoryAdapter, self)._call(method, arguments) 
File "/opt/openerp7/git/connector-magento/magentoerpconnect/unit/backend_adapter.py", line 156, in _call result = api.call(method, arguments) 
File "/opt/openerp7/git/openerp/tools/eggs/magento-0.4-py2.7.egg/magento/api.py", line 161, in call return self.client.call(self.session, resource_path, arguments) 
File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__ return self.__send(self.__name, args) 
File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request verbose=self.__verbose 
File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request return self.single_request(host, handler, request_body, verbose) 
File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request return self.parse_response(response) 
File "/usr/lib/python2.7/xmlrpclib.py", line 1473, in parse_response return u.close() 
File "/usr/lib/python2.7/xmlrpclib.py", line 793, in close raise 
Fault(**self._stack[0]) 
Fault: <Fault 1: 'Internal Error. Please see log for details.'>

```

**Comment by guewen** [comment]
The errors that starts with `Fault` are errors returned by Magento.
Here, it is an internal error in Magento.

It may be caused by:
- The connector calls Magento with erroneous values
- A bug or invalid data in Magento
- A customization on Magento that prevent it to respond correctly to a request

Lately I have a handful of the 2 last options, but the only way to know what the problem is, is to take a deep breath and plunge in the Magento logs or take a PHP debugger (I can't do that, I ask someone to do it).

What you may want to do is to first dump the method and the arguments sent to Magento so you can reproduce it more readily.
