### ISSUE TITLE
Error when importing a sale record from magento 1.9.x into odoo 8.x

### ISSUE THREAD

**Issue by ghost** [OCA/connector-magento#96]
Dear developer,

Thank you for developing an import extension for magento to Odoo.
Currently I have succeded to import the customer/categories and products into Odoo from magento. Unfortunetly I have some problems with importing sale orders.

I hope you can provide me with a solution for this problem.

Thank you in advance,

Michiel

---

The following error appears: 
MissingError: ('MissingError', u'One of the documents you are trying to access has been deleted, please try again after refreshing.')

More traceback information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/openerp/addons/magento/magento-connector-v8/connector/queue/worker.py", line 127, in run_job
    with session_hdl.session() as session:
  File "/usr/lib/python2.7/site-packages/openerp/addons/magento/magento-connector-v8/connector/queue/job.py", line 492, in perform
    descr = (self._description or
  File "/usr/lib/python2.7/site-packages/openerp/addons/magento/magento-connector-v8/magentoerpconnect/unit/import_synchronizer.py", line 378, in import_record
    importer.run(magento_id, force=force)
  File "/usr/lib/python2.7/site-packages/openerp/addons/magento/magento-connector-v8/magentoerpconnect/unit/import_synchronizer.py", line 229, in run
    record = self._create_data(map_record)
  File "/usr/lib/python2.7/site-packages/openerp/addons/magento/magento-connector-v8/magentoerpconnect/sale.py", line 826, in _create_data
    *_kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/magento/magento-connector-v8/magentoerpconnect/unit/import_synchronizer.py", line 170, in _create_data
    return map_record.values(for_create=True, *_kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/magento/magento-connector-v8/connector/unit/mapper.py", line 910, in values
    def __getattr__(self, key):
  File "/usr/lib/python2.7/site-packages/openerp/addons/magento/magento-connector-v8/connector/unit/mapper.py", line 643, in _apply

  File "/usr/lib/python2.7/site-packages/openerp/addons/magento/magento-connector-v8/connector/unit/mapper.py", line 701, in _apply_with_options
    'mapping method %s' % (values, meth))
  File "/usr/lib/python2.7/site-packages/openerp/addons/magento/magento-connector-v8/magentoerpconnect/sale.py", line 929, in finalize
    values = self._add_shipping_line(map_record, values)
  File "/usr/lib/python2.7/site-packages/openerp/addons/magento/magento-connector-v8/magentoerpconnect/sale.py", line 895, in _add_shipping_line
    line = (0, 0, line_builder.get_line())
  File "/usr/lib/python2.7/site-packages/openerp/addons/magento/magento-connector-v8/connector_ecommerce/sale.py", line 490, in get_line
    'name': product.name,
  File "/usr/lib/python2.7/site-packages/openerp/fields.py", line 823, in __get__
    return record._cache[self]
  File "/usr/lib/python2.7/site-packages/openerp/models.py", line 5913, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "/usr/lib/python2.7/site-packages/openerp/fields.py", line 55, in get
    raise self.exception

**Comment by guewen** [comment]
Hi,

Is it the only logs you had? If you run the same import with the DEBUG logs, what is displayed before the error? It should display the operations and the data it was importing.

**Comment by guewen** [comment]
No answer so I close this issue.

**Comment by ghost** [comment]
Thank you for your email Guewen. Unfortunately I have deleted the extension and bought a paid one. I can't check the logs now. 
However if you import sales order you shall get the error.

**Comment by guewen** [comment]
@MichielTG We don't get the error you reported that's why I asked you more details. Anyway it is no longer relevant if you don't use this connector, thanks anyway for reporting.

**Comment by guewen** [comment]
For the record: reading the logs again, my guess is that the "Shipping" product has been deleted. But I can't be sure without more details.

**Comment by ghost** [comment]
Thank you for your email, because I have multiple problems with the paid version. Maybe I will try the installation again later this month. Still thanks for your reply and suggestions. 
I still prefer Open Source ;)
